"""auto update

Revision ID: a6ca136581f3
Revises: f7e24a988ac2
Create Date: 2026-03-20 02:48:45.248394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ca136581f3'
down_revision: Union[str, Sequence[str], None] = 'f7e24a988ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('listing_title', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('input_data', sa.String(), nullable=True),
    sa.Column('score_function_expression', sa.Float(), nullable=True),
    sa.Column('score_scenario_expression', sa.Float(), nullable=True),
    sa.Column('score_identity_fit', sa.Float(), nullable=True),
    sa.Column('score_psychology_benefit', sa.Float(), nullable=True),
    sa.Column('score_risk_elimination', sa.Float(), nullable=True),
    sa.Column('score_differentiation', sa.Float(), nullable=True),
    sa.Column('diagnosis_report', sa.String(), nullable=True),
    sa.Column('keyword_report', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_diagnoses_id'), 'listing_diagnoses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_diagnoses_id'), table_name='listing_diagnoses')
    op.drop_table('listing_diagnoses')
    # ### end Alembic commands ###