"""auto update

Revision ID: d8a66af4ad50
Revises: 47c566e39fcb
Create Date: 2026-03-16 09:08:55.602829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a66af4ad50'
down_revision: Union[str, Sequence[str], None] = '47c566e39fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_name', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_data_id'), 'ad_data', ['id'], unique=False)
    op.create_table('ad_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_recommendations_id'), 'ad_recommendations', ['id'], unique=False)
    op.create_table('cosmo_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('optimized_title', sa.String(), nullable=True),
    sa.Column('optimized_bullets', sa.String(), nullable=True),
    sa.Column('optimized_keywords', sa.String(), nullable=True),
    sa.Column('analysis_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosmo_results_id'), 'cosmo_results', ['id'], unique=False)
    op.create_table('health_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title_score', sa.Integer(), nullable=True),
    sa.Column('keyword_score', sa.Integer(), nullable=True),
    sa.Column('bullet_score', sa.Integer(), nullable=True),
    sa.Column('aplus_score', sa.Integer(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('suggestions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reports_id'), 'health_reports', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bullet_points', sa.String(), nullable=True),
    sa.Column('a_plus_content', sa.String(), nullable=True),
    sa.Column('search_keywords', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_health_reports_id'), table_name='health_reports')
    op.drop_table('health_reports')
    op.drop_index(op.f('ix_cosmo_results_id'), table_name='cosmo_results')
    op.drop_table('cosmo_results')
    op.drop_index(op.f('ix_ad_recommendations_id'), table_name='ad_recommendations')
    op.drop_table('ad_recommendations')
    op.drop_index(op.f('ix_ad_data_id'), table_name='ad_data')
    op.drop_table('ad_data')
    # ### end Alembic commands ###