"""auto update

Revision ID: f7e24a988ac2
Revises: a8077900e9c4
Create Date: 2026-03-20 01:13:00.975817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e24a988ac2'
down_revision: Union[str, Sequence[str], None] = 'a8077900e9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asin_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('product_title', sa.String(), nullable=True),
    sa.Column('product_data', sa.String(), nullable=True),
    sa.Column('score_functionality', sa.Float(), nullable=True),
    sa.Column('score_emotional', sa.Float(), nullable=True),
    sa.Column('score_scenario', sa.Float(), nullable=True),
    sa.Column('score_user_profile', sa.Float(), nullable=True),
    sa.Column('score_differentiation', sa.Float(), nullable=True),
    sa.Column('score_market_trend', sa.Float(), nullable=True),
    sa.Column('analysis_report', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asin_analyses_id'), 'asin_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asin_analyses_id'), table_name='asin_analyses')
    op.drop_table('asin_analyses')
    # ### end Alembic commands ###