"""auto update

Revision ID: 17534fe3a638
Revises: ecd08c6af770
Create Date: 2026-03-30 02:26:09.723525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17534fe3a638'
down_revision: Union[str, Sequence[str], None] = 'ecd08c6af770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_asin', sa.String(), nullable=False),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('gaps', sa.String(), nullable=True),
    sa.Column('suggestions', sa.String(), nullable=True),
    sa.Column('radar_scores', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_insights_id'), 'competitor_insights', ['id'], unique=False)
    op.create_table('consumer_intent_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('total_keywords', sa.Integer(), nullable=True),
    sa.Column('high_freq_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_intent_results_id'), 'consumer_intent_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_intent_results_id'), table_name='consumer_intent_results')
    op.drop_table('consumer_intent_results')
    op.drop_index(op.f('ix_competitor_insights_id'), table_name='competitor_insights')
    op.drop_table('competitor_insights')
    # ### end Alembic commands ###